version: '3.7'
services:
  db-consistent:
    image: postgres:12.2
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - "consistent:/var/lib/postgresql/data:consistent"
  db-cached:
    image: postgres:12.2
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - "cached:/var/lib/postgresql/data:cached"

volumes:
  consistent:
  cached:
